구현모 자료구조 1주차 과제 제출
2022-DKUS-Summer-Study/Data-Structure pull request #15
Opened 2022-07-11 08:21 UTC by hmooko

과제 제출

2022-07-11 09:28 UTC, LMS1229 commented on 현모/1주차/array_sample.c
> +        array->arr = (int*)realloc(array->arr, sizeof(int) * array->capacity * 2);
만약 realloc 함수를 썼을 때, 재할당에 실패하면 어떻게 되나요?

2022-07-11 09:33 UTC, LMS1229 commented on 현모/1주차/array_sample.c
> +    if (array->arr[0] != NULL || (array->size < index && index < 0))
수정 바랍니다. 올바르게 동작하지 않습니다. 
case 1.
{1,2,3,6,1,2,-1,...} 인 배열이라면 그 어떤 값도 삭제할 수 없습니다.

case 2.
capacity 가 4, size가 4인 상황에서 index 값으로 4가 들어온다면 delete 연산은 수행할 수 없으나, 수행에 성공했음을 표시시하게 됩니다.

2022-07-11 10:42 UTC, hmooko commented on 현모/1주차/array_sample.c
> +        array->arr = (int*)realloc(array->arr, sizeof(int) * array->capacity * 2);
null을 반환하고 메모리 주소를 알 수 없어 메모리 누수가 발생합니다

2022-07-11 10:58 UTC, hmooko commented on 현모/1주차/array_sample.c
> +    if (array->arr[0] != NULL || (array->size < index && index < 0))
수정했습니다!!

2022-07-11 11:47 UTC, LMS1229 commented on 현모/1주차/array_sample.c
> +        array->arr = (int*)realloc(array->arr, sizeof(int) * array->capacity * 2);
네 좋습니다!

2022-07-11 11:47 UTC, LMS1229 approved these changes
잘하셨습니다~!

2022-07-12 04:11 UTC, developerChans requested changes
파일의 맨 끝에는 공백이 있어야합니다. 따라서 116번째 줄에서 엔터를 한번 더 쳐주시면 좋습니다.
참고 링크입니다.
https://jihyehwang09.github.io/2020/04/09/no-newline-at-end-of-file/

2022-07-12 04:11 UTC, developerChans commented on 현모/1주차/array_sample.h
> +int delete (int_array* array, const int index);
Add EOF

2022-07-12 04:11 UTC, developerChans commented on 현모/1주차/main.c
> +}
Add EOF

2022-07-12 07:44 UTC, LMS1229 commented on 현모/1주차/array_sample.c
> +    if (array->size >= index && index < 0)
size가 5이고 index 가 2이면 접근 가능한데 불가능하다고 표시하고 있습니다

2022-07-13 05:25 UTC, LMS1229 requested changes
코멘트 내용을 토대로 수정해주세요

2022-07-13 12:36 UTC, LMS1229 commented on 현모/1주차/array_sample.c
> +    if (array->size >= index && index < 0)
size 값이 5인 경우, index가 10이면 peek연산은 실패해야 하지만 이 경우엔 if 문 조건에 맞지 않습니다.

2022-07-17 09:12 UTC, LMS1229 approved these changes
좋습니다~!

2022-07-17 23:36 UTC, developerChans approved these changes

2022-07-17 23:36 UTC, merged