배건우/1주차/자료구조
2022-DKUS-Summer-Study/Data-Structure pull request #17
Opened 2022-07-12 11:42 UTC by CodeItpython

2022-07-12 11:45 UTC, developerChans approved these changes

2022-07-13 05:13 UTC, LMS1229 commented on 배건우/1주차/sample.c
> +  if ((index >= 0) && (index <= array->size)) // index�� ��� ���� �ִ°��
array의 capacity가 5, size가 5 일때 insert 연산을 하면 오버 플로우가 발생합니다.

2022-07-13 05:14 UTC, LMS1229 commented on 배건우/1주차/sample.c
> +  if (index < 0 && index >= array->size) //�ε����� ������� ����� 0����
peek 연산 실패시, 0 반환이 아닌 프로그램을 종료해주세요

2022-07-13 05:14 UTC, LMS1229 commented on 배건우/1주차/sample.c
> +    realloc(array->ptr, sizeof(int) * (array->capacity * 2)); //���Ҵ�+capacity�� 2�� �÷���
realloc 함수에서 재할당을 실패하면 어떻게 되나요?

2022-07-13 05:16 UTC, LMS1229 commented on 배건우/1주차/sample.c
> +  else if (array->ptr[index] && index >= 0 && index <= array->size) // ptr[index]�� ���� ����� ���  (����� �Ǵ°��)
index에 존재하는 값이 0 이면 삭제가 수행되지 않습니다.

2022-07-13 05:16 UTC, LMS1229 requested changes
코멘트 내용을 토대로 수정 바랍니다

2022-07-13 08:52 UTC, CodeItpython commented on 배건우/1주차/sample.c
> +  if ((index >= 0) && (index <= array->size)) // index�� ��� ���� �ִ°��
조건문 1개 추가해서 수정했습니다!

2022-07-13 08:52 UTC, CodeItpython commented on 배건우/1주차/sample.c
> +  if (index < 0 && index >= array->size) //�ε����� ������� ����� 0����
exit(1)코드 추가하는것으로 수정했습니다

2022-07-13 08:52 UTC, CodeItpython commented on 배건우/1주차/sample.c
> +  else if (array->ptr[index] && index >= 0 && index <= array->size) // ptr[index]�� ���� ����� ���  (����� �Ǵ°��)
main.c에서 index 0 삭제를 통해 수행을 확인했습니다!

2022-07-13 09:16 UTC, LMS1229 commented on 배건우/1주차/sample.c
> +  else if (array->ptr[index] && index >= 0 && index <= array->size) // ptr[index]�� ���� ����� ���  (����� �Ǵ°��)
배열이 [0,1,2,3,4] 상태일 때, 0번째 인덱스 값을 delete 해보시길 바랍니다

2022-07-13 12:32 UTC, LMS1229 requested changes
다른 스터디원 분들의 폴더를 삭제하지 않으신 상태로 PR 해주세요

2022-07-14 00:09 UTC, developerChans requested changes
다른 스터디원의 폴더들을 삭제하셨습니다. 또한 공용폴더  LICENSE도 포함이구요...  저번 스터디 강의때 분명 다른 스터디원의 폴더 및 다른 폴더랑 파일을 삭제 또는 변경을 지양한다고 공지햇던 것 같은데... 
저번에 제가 보정해 드렸는데 다른 스터디원들의 폴더를 삭제하시는 이유가 뭘까요?

2022-07-14 04:30 UTC, closed without merging