정도현 자료구조 1주차 과제 제출
2022-DKUS-Summer-Study/Data-Structure pull request #20
Opened 2022-07-14 09:22 UTC by JungDohyeon

realloc 부분 수정 했습니다! (insert, push)

2022-07-15 00:12 UTC, developerChans commented
https://github.com/2022-DKUS-Summer-Study/Data-Structure/pull/16

2022-07-15 12:41 UTC, LMS1229 commented on 도현/1주차/array_setting.c
> +    if(index < 0 || index > array->size){
index가 array->size  와 같다면  오버 플로우가 발생합니다

2022-07-15 12:41 UTC, LMS1229 requested changes
코멘트 내용을 참고해 수정해주시길 바랍니다

2022-07-16 09:21 UTC, JungDohyeon commented on 도현/1주차/array_setting.c
> +    if(index < 0 || index > array->size){
수정해서 다시 올리겠습니다!

2022-07-17 09:11 UTC, LMS1229 approved these changes
종습니다!

2022-07-17 23:41 UTC, developerChans approved these changes

2022-07-17 23:42 UTC, merged