배건우/자료구조/2주차 과제
2022-DKUS-Summer-Study/Data-Structure pull request #21
Opened 2022-07-17 05:13 UTC by CodeItpython

2022-07-17 09:00 UTC, LMS1229 commented on 배건우/1주차/list.c
> +  else if (array->ptr[index] && index >= 0 && index <= array->size) // ptr[index]�� ���� ����� ���  (����� �Ǵ°��)
array->ptr[index] 에 저장된 값이 0이라면 값이 삭제 되지 않습니다.

2022-07-17 09:01 UTC, LMS1229 commented on 배건우/2주차/double_linked_list/linked_list.c
> +    if (nowNode->data = target)
target 이 0.0f 면 언제나 NULL 을 반환하고 리스트 내의 모든 노드에 존재하는 데이터가 0.0f 로 바뀝니다.

2022-07-17 09:05 UTC, LMS1229 commented on 배건우/2주차/double_linked_list/linked_list.c
> +  list->head = create_node(0);
list는 초기에 어떤 데이터(노드) 도 존재해선 안됩니다

2022-07-17 09:06 UTC, LMS1229 commented on 배건우/2주차/double_linked_list/linked_list.c
> +  if (target_node == NULL)
target_node가 마지막 노드의 뒤가 되면 삽입이 이루어지지 않습니다.

2022-07-17 09:08 UTC, LMS1229 requested changes
코멘트 내용을 토대로 수정바랍니다

2022-07-17 10:20 UTC, CodeItpython commented on 배건우/2주차/double_linked_list/linked_list.c
> +  list->head = create_node(0);
init메소드에서 NULL로 초기화를 해줘야하는데 create_node메소드의 파라미터로 float형 데이터만 집어넣을수있는데 어떻게 초기화해야할지 모르겠네요...

2022-07-17 13:59 UTC, CodeItpython commented on 배건우/2주차/double_linked_list/linked_list.c
> +  if (target_node == NULL)
위의 조건문의 경우 previous_node가 list->tail일 경우이니까 조건문안에 push_back(list->tail,value)로 넣으면 해결되는건가요?

2022-07-18 13:41 UTC, LMS1229 commented on 배건우/2주차/double_linked_list/linked_list.c
> +void init(float_double_linked_list *list) // list �ʱ�ȭ
초기화가 제대로 이루어지지 않습니다.

2022-07-18 13:42 UTC, LMS1229 commented on 배건우/2주차/double_linked_list/linked_list.c
> +  if (target_node == NULL)
push_back 연산의 경우, 새로운 노드를 생성한 후, tail이 가리키는 노드의 다음 노드를 해당 노드로 바꾼 뒤 tail 이 가리키는 노드를 바꾸면 됩니다.

2022-07-19 01:24 UTC, LMS1229 commented on 배건우/2주차/double_linked_list/linked_list.c
> +  list->head = create_node(0);
예제와 같이 수행하시면 됩니다

2022-07-20 08:55 UTC, CodeItpython commented on 배건우/2주차/double_linked_list/linked_list.c
> +    if (nowNode->data = target)
if 문 수정완료했습니다!

2022-07-20 08:56 UTC, CodeItpython commented on 배건우/2주차/double_linked_list/linked_list.c
> +  list->head = create_node(0);
초기화 수정했습니다!

2022-07-20 09:26 UTC, CodeItpython commented on 배건우/2주차/double_linked_list/linked_list.c
> +  if (target_node == NULL)
초기화메소드 수정후 push_back연산에 조건문을 추가해 수정했습니다
또한 push_back,front연산과 마찬가지로 delete_back,front연산도 새로 만들어주었습니다

2022-07-20 09:26 UTC, CodeItpython commented on 배건우/2주차/double_linked_list/linked_list.c
> +void init(float_double_linked_list *list) // list �ʱ�ȭ
초기화 수정했습니다!

2022-07-20 23:31 UTC, LMS1229 commented on 배건우/2주차/double_linked_list/linked_list.c
> +    list->head = list->tail = newNode;
이중 원형 연결 리스트가 됩니다. 원형 형태가 되지 않도록 수정해주세요

2022-07-25 00:16 UTC, developerChans approved these changes

2022-07-26 12:09 UTC, closed without merging