윤영은 자료구조 2주차 과제 제출
2022-DKUS-Summer-Study/Data-Structure pull request #22
Opened 2022-07-19 14:47 UTC by 0eun0314

2022-07-20 04:10 UTC, LMS1229 commented on 윤영은/2주차/README.md
> +���԰� ��� �����ϴ�.
연결리스트가 배열에 비해 삽입,삭제가 용이한 이유가 무엇인가요?

2022-07-20 04:13 UTC, LMS1229 commented on 윤영은/2주차/linked_list_2.c
> +        if (index == 0) {
연산이 제대로 수행되지 않습니다.

2022-07-20 04:14 UTC, LMS1229 commented on 윤영은/2주차/linked_list_2.c
> +void push_front(float_double_linked_list* list, const float value) {
리스트가 비어있을 때, 제대로 동작하지 않습니다.

2022-07-20 04:14 UTC, LMS1229 requested changes
코멘트를 토대로 수정해주세요

2022-07-20 09:20 UTC, 0eun0314 commented on 윤영은/2주차/README.md
> +���԰� ��� �����ϴ�.
배열은 삽입, 삭제를 하기 위해서는 해당 위치 이후의 값들을 모두 복사(이동)시켜야 하고 삽입의 경우 배열의 크기가 충분히 크지 않으면 삽입이 불가능하지만, 연결리스트는 각 데이터들이 포인터를 통해 연결되어 있기 때문에 이를 수정하는 방식으로 비교적으로 간단하게 삽입과 삭제 연산을 수행할 수 있기 때문입니다.

2022-07-20 09:41 UTC, 0eun0314 commented on 윤영은/2주차/linked_list_2.c
> +        if (index == 0) {
혹시 어느 부분에서 연산 문제가 발생하는지 설명해주실 수 있을까요?

2022-07-20 09:45 UTC, 0eun0314 commented on 윤영은/2주차/linked_list_2.c
> +void push_front(float_double_linked_list* list, const float value) {
수정했습니다!!

2022-07-20 23:25 UTC, LMS1229 commented on 윤영은/2주차/linked_list_2.c
> +        if (index == 0) {
index가 0이면 원래 head 노드 H의 이전 노드가 H가 됩니다.

2022-07-22 03:41 UTC, developerChans approved these changes

2022-07-22 04:39 UTC, 0eun0314 commented on 윤영은/2주차/linked_list_2.c
> +        if (index == 0) {
넵 확인하고 수정했습니다!!

2022-07-25 10:17 UTC, LMS1229 approved these changes
좋습니다~!

2022-07-25 10:17 UTC, merged