자료구조 4주차 과제 제출
2022-DKUS-Summer-Study/Data-Structure pull request #27
Opened 2022-08-01 09:42 UTC by JungDohyeon

자료구조 4주차 과제 제출합니다!

2022-08-01 23:56 UTC, developerChans approved these changes
git 제출 상태는 Good!

2022-08-02 05:12 UTC, LMS1229 commented on 도현/4주차/graph.c
> +void DFS(weighted_undirected_graph* graph, int u){
메모리 누수가 발생합니다.

2022-08-02 05:15 UTC, LMS1229 commented on 도현/4주차/graph.c
> +    while(top != -1) {
그래프의 정점이 6개 있고 그래프에 존재하는 간선이 다음과 같을 때, 스택의 오버 플로우가 발생합니다.
0 1
1 2
2 3
0 4
2 4
3 4
0 5
1 5
3 5

2022-08-02 05:16 UTC, LMS1229 commented on 도현/4주차/graph.c
> +void BFS(weighted_undirected_graph* graph, int u){
메모리 누수가 발생합니다.

2022-08-02 05:17 UTC, LMS1229 commented on 도현/4주차/main.c
> +    graph->arr = (int **)malloc(sizeof(int *) * n);
그래프 구조체에 대한 초기화는 init 함수에서 수행해주세요

2022-08-02 05:17 UTC, LMS1229 requested changes
코멘트 내용을 토대로 수정해주시길 바랍니다.

2022-08-03 07:17 UTC, JungDohyeon commented on 도현/4주차/graph.c
> +void DFS(weighted_undirected_graph* graph, int u){
> 코멘트 내용을 토대로 수정해주시길 바랍니다.

네 알겠습니다!

2022-08-03 07:21 UTC, JungDohyeon commented
> 코멘트 내용을 토대로 수정해주시길 바랍니다.

네 알겠습니다!

2022-08-03 08:45 UTC, LMS1229 approved these changes
좋습니다!

2022-08-03 08:45 UTC, merged