정도현 4주차 과제 제출
2022-DKUS-Summer-Study/Data-Structure pull request #30
Opened 2022-08-04 06:45 UTC by JungDohyeon

DFS (stack의 오버플로우 방지) 수정하여 재 제출 합니다!

2022-08-05 02:45 UTC, LMS1229 commented on 도현/4주차/graph.c
> +void DFS(weighted_undirected_graph* graph, int u){
다음과 같은 그래프에서 DFS 결과가 올바르지 않습니다.

![DFS 오답 예제](https://user-images.githubusercontent.com/32133660/182990341-93fd396b-ecae-40bf-97cd-492ec730d98f.png)
다

2022-08-05 02:45 UTC, LMS1229 requested changes
코멘트 내용을 토대로 수정 바랍니다.

2022-08-05 12:06 UTC, JungDohyeon commented on 도현/4주차/graph.c
> +void DFS(weighted_undirected_graph* graph, int u){
예시로 주신 그래프 넣어서 DFS 탐색을 해보았는데 제가 생각하기론 DFS순서 맞게 작동하는 것 같은데 어느 부분 순서가 틀린지 잘 모르겠습니다 ㅠㅠ
아래는 실행 후 출력 된 결과입니다!

시작 정점 0: 0 3 6 7 5 2 4 1 
시작 정점 1: 1 4 7 6 3 0 2 5 
시작 정점 2: 2 5 7 6 3 0 1 4 
시작 정점 3: 3 6 7 5 2 0 1 4 
시작 정점 4: 4 7 6 3 0 2 5 1 
시작 정점 5: 5 7 6 3 0 2 1 4 
시작 정점 6: 6 7 5 2 0 3 1 4 
시작 정점 7:  7 6 3 0 2 5 1 4 

-> 같은 Depth에 있을 때 정점 숫자가 높은 것이 먼저 탐색되도록 했습니다!

2022-08-06 03:05 UTC, LMS1229 commented on 도현/4주차/graph.c
> +void DFS(weighted_undirected_graph* graph, int u){
제가 코드를 잘못 봤습니다 죄송합니다...

2022-08-06 03:06 UTC, LMS1229 approved these changes
수고하셨습니다!

2022-08-06 04:50 UTC, developerChans approved these changes

2022-08-06 04:50 UTC, merged