배건우 자료구조 5주차 과제제출
2022-DKUS-Summer-Study/Data-Structure pull request #31
Opened 2022-08-04 11:53 UTC by CodeItpython

2022-08-05 02:29 UTC, LMS1229 commented on 배건우/5주차/sample.c
> +        child = cur * 2;
삭제가 정확하게 이루어지지 않습니다.

2022-08-05 02:31 UTC, LMS1229 commented on 배건우/5주차/main.c
> +    for (int i = 0;i < 10;i++) {    //힙정렬 실행
heap_sort 으로 정렬할 배열 index의 범위는 [1,n] 입니다.

2022-08-05 02:36 UTC, LMS1229 requested changes
코멘트 내용을 토대로 수정 바랍니다

2022-08-05 07:20 UTC, CodeItpython commented on 배건우/5주차/sample.c
> +        child = cur * 2;
pop메소드 수정 및 주석처리완료했습니다

2022-08-06 02:48 UTC, LMS1229 approved these changes
좋습니다~!

2022-08-06 04:51 UTC, developerChans requested changes
IDLE 폴더가 과제에 포함되어있습니다 추후에 수정해드리겠습니다

2022-08-13 05:37 UTC, closed without merging