김다은 자료구조 스터디 0주차 과제 제출
2022-DKUS-Summer-Study/Data-Structure pull request #6
Opened 2022-07-06 10:59 UTC by Dara-Kim

2022-07-06 23:42 UTC, developerChans requested changes

2022-07-06 23:42 UTC, developerChans commented on Dara-Kim/0주차/0주차 과제.c
> +}
파일의 맨 끝에는 공백이 있어야합니다. 따라서 116번째 줄에서 엔터를 한번 더 쳐주시면 좋습니다.
참고 링크입니다.
https://jihyehwang09.github.io/2020/04/09/no-newline-at-end-of-file/

2022-07-06 23:42 UTC, developerChans commented on Dara-Kim/0주차/0주차 과제.c
> +	arr_2 = (int*)calloc(5, sizeof(int));	// sizoe(int)ũ���� ���� 5�� ������ �� �ִ� ���Ҵ�
malloc과 calloc의 차이가 무엇이 있을까요?

2022-07-06 23:42 UTC, developerChans commented on Dara-Kim/0주차/0주차 과제.c
> +	arr_2 = (int*)malloc(sizeof(int) * 5);	// �޸� �Ҵ�, �迭�� ũ�⸸ŭ �Ҵ��ϱ� ��� 5�� ����
혹시 arr_2가 double 형일 경우엔 어떤 식으로 메모리 할당을 해주어야 할까요?

2022-07-08 04:38 UTC, LMS1229 commented on Dara-Kim/0주차/0주차 과제.c
> +	free(arr_2);	// free�Լ� �̿��Ͽ� �޸� ���
free를 한 후엔 arr_2는 어떤 값을 가지고 있나요?

2022-07-08 04:38 UTC, LMS1229 commented on Dara-Kim/0주차/0주차 과제.c
> +	realloc(arr_2, sizeof(int) * 10);	// arr_2�� �޸𸮸� 40����Ʈ�� �� �Ҵ�
realloc 은 한 뒤, arr_2의 값은 어떻게 변하나요?

2022-07-08 13:15 UTC, Dara-Kim commented on Dara-Kim/0주차/0주차 과제.c
> +	arr_2 = (int*)calloc(5, sizeof(int));	// sizoe(int)ũ���� ���� 5�� ������ �� �ִ� ���Ҵ�
malloc은 size에 해당하는 크기만큼의 메모리를 바이트 단위로 할당하고, calloc은 주어진 size만큼의 메모리를 주어진 count만큼 할당합니다. 따라서 malloc은 calloc과 다르게 배열의 크기만큼 할당해주기 위해서는 주어진 size에 배열의 크기만큼을 곱해줘야 합니다.

2022-07-08 13:15 UTC, Dara-Kim commented on Dara-Kim/0주차/0주차 과제.c
> +	arr_2 = (int*)malloc(sizeof(int) * 5);	// �޸� �Ҵ�, �迭�� ũ�⸸ŭ �Ҵ��ϱ� ��� 5�� ����
`arr_2 = (double*)malloc(sizeof(double) * 5);` 으로 고치면 될 것 같습니다.

2022-07-08 13:15 UTC, Dara-Kim commented on Dara-Kim/0주차/0주차 과제.c
> +	free(arr_2);	// free�Լ� �̿��Ͽ� �޸� ���
이전과 같은 값을 가지고 있습니다. 아마 메모리 해제는 되었지만 해제 후에 따로 초기화가 되지 않는 것 같아 보입니다.

2022-07-08 13:16 UTC, Dara-Kim commented on Dara-Kim/0주차/0주차 과제.c
> +	realloc(arr_2, sizeof(int) * 10);	// arr_2�� �޸𸮸� 40����Ʈ�� �� �Ҵ�
arr_2는 이전에 크기 5만 할당 받은 상태로 1 2 3 4 5를 저장하고 있었기 때문에 realloc을 한 뒤에 할당 받은 크기가 10이 되자 기존의 1 2 3 4 5는 유지한 채로 인덱스 5부터 9까지는 쓰레기값을 가지게 되었습니다.

2022-07-08 14:28 UTC, LMS1229 commented on Dara-Kim/0주차/0주차 과제.c
> +	free(arr_2);	// free�Լ� �̿��Ͽ� �޸� ���
네 좋습니다!

2022-07-08 14:29 UTC, LMS1229 commented on Dara-Kim/0주차/0주차 과제.c
> +	realloc(arr_2, sizeof(int) * 10);	// arr_2�� �޸𸮸� 40����Ʈ�� �� �Ҵ�
맞습니다. 따로 값을 지정하지 않아 쓰레기값이 저장되어 있습니다. 그러면 realloc을 한 뒤, arr_2 변수에 저장된 주소값은 항상 같은 값을 가지나요??

2022-07-09 00:44 UTC, developerChans commented on Dara-Kim/0주차/0주차 과제.c
> +	arr_2 = (int*)calloc(5, sizeof(int));	// sizoe(int)ũ���� ���� 5�� ������ �� �ִ� ���Ҵ�
이 부분은 개인톡으로 드린 것 처럼 malloc 과 calloc 의 차이는 초기화가 되냐 안되냐입니다.
또한 calloc도 calloc(1,sizeof(int)*5) 가 가능합니당

2022-07-09 00:44 UTC, developerChans commented on Dara-Kim/0주차/0주차 과제.c
> +	arr_2 = (int*)malloc(sizeof(int) * 5);	// �޸� �Ҵ�, �迭�� ũ�⸸ŭ �Ҵ��ϱ� ��� 5�� ����
오 동적할당에 대해 확실하게 잘 아시는 군용

2022-07-09 05:50 UTC, Dara-Kim commented on Dara-Kim/0주차/0주차 과제.c
> +	realloc(arr_2, sizeof(int) * 10);	// arr_2�� �޸𸮸� 40����Ʈ�� �� �Ҵ�
realloc 함수는 동적할당된 메모리의 내용을 유지하면서 메모리 크기를 변경해주는 함수인데, 보통은 재할당될 때 해당 주소에서 사용자가 요구한 크기만큼 연속되게 할당을 해줍니다. 그러나 요구한 크기만큼 연속되게 메모리를 확보할 수 없다면 다른 공간에서 메모리를 확보하기도 합니다. 이 경우에도 해당 메모리가 가지고 있던 내용은 그대로 유지가 되는 것으로 알고 있습니다.

2022-07-09 08:20 UTC, closed without merging