배건우 / 2022 dkus summer study / data-strucure / 1주차 과제제출
2022-DKUS-Summer-Study/Data-Structure pull request #7
Opened 2022-07-10 07:23 UTC by CodeItpython

2022-07-10 08:32 UTC, LMS1229 commented on 과제/1주차/sample.c
> +  array->ptr = (int *)malloc(sizeof(int) * 100);
capacity 와 동적 할당한 배열의 길이가 다른 이유가 있나요??

2022-07-10 08:33 UTC, LMS1229 commented on 과제/1주차/sample.c
> +  if (!is_full(array) && (index >= 0) && (index <= array->size))
배열이 가득차도 index 가 유효한 범위라면 insert 연산은 가능합니다

2022-07-10 08:34 UTC, LMS1229 commented on 과제/1주차/sample.c
> +  else if (array->ptr[index])
array->ptr[index]의 어떤 수가 저장 되어도 삭제연산이 올바르게 동작하나요?

2022-07-10 08:37 UTC, LMS1229 commented on 과제/1주차/sample.c
> +    realloc(array->ptr, sizeof(int) * 200);
realloc 을 한 뒤, array->ptr에 저장된 주소는 변경될 수 있습니다. 그렇게 된다면 realloc 이전에 할당 받은 메모리는 해제되지 않아, 메모리 누수가 발생할 수 있습니다.

2022-07-10 08:38 UTC, LMS1229 requested changes
코멘트 내용에 맞추어, 수정해주시기 바랍니다.

2022-07-11 00:25 UTC, developerChans requested changes
추가적으로 폴더구조는
배건우/1주차/ 
내에 과제가 있어야합니다. 잘 모르시겠다면 연락주세요!!

파일의 맨 끝에는 공백이 있어야합니다. 따라서 116번째 줄에서 엔터를 한번 더 쳐주시면 좋습니다.
참고 링크입니다.
https://jihyehwang09.github.io/2020/04/09/no-newline-at-end-of-file/

2022-07-11 00:25 UTC, developerChans commented on 과제/1주차/main.c
> +}
공백 EOF 추가

2022-07-11 00:25 UTC, developerChans commented on 과제/1주차/sample.c
> +}
공백 EOF 추가

2022-07-11 00:25 UTC, developerChans commented on 과제/1주차/sample.h
> +void print_arr(int_array *array);
공백 EOF 추가

2022-07-12 11:32 UTC, closed without merging